[project]
name = "oiv2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litellm>=1.65.0",
    "openai>=1.69.0",
    "openai-agents>=0.0.7",
    "pydantic>=2.11.1",
]
